# @formatter:off

[build]
incremental = false
jobs        = 2

#---------------------------------- Windows MSVC x86 (enable large address space, remove unreferenced code/data, identical code folding (merge duplicate code))
[target.i686-pc-windows-msvc]
linker    = 'C:\Program Files\Microsoft Visual Studio\18\Community\VC\Tools\MSVC\14.51.36231\bin\Hostx64\x86\link.exe'
ar        = 'C:\Program Files\Microsoft Visual Studio\18\Community\VC\Tools\MSVC\14.51.36231\bin\Hostx64\x86\lib.exe'
rustflags = ['-C', 'link-arg=/LARGEADDRESSAWARE',
             '-C', 'link-arg=/OPT:REF',
             '-C', 'link-arg=/OPT:ICF',
             '-C', 'link-arg=/DEBUG:NONE',
            ]

[target.x86_64-pc-windows-msvc]
linker    = 'C:\Program Files\Microsoft Visual Studio\18\Community\VC\Tools\MSVC\14.51.36231\bin\Hostx64\x64\link.exe'
ar        = 'C:\Program Files\Microsoft Visual Studio\18\Community\VC\Tools\MSVC\14.51.36231\bin\Hostx64\x64\lib.exe'
rustflags = ['-C', 'link-arg=/OPT:REF',
             '-C', 'link-arg=/OPT:ICF',
             '-C', 'link-arg=/DEBUG:NONE',
            ]

[target.aarch64-pc-windows-msvc]
linker    = 'C:\Program Files\Microsoft Visual Studio\18\Community\VC\Tools\MSVC\14.51.36231\bin\Hostx64\arm64\link.exe'
ar        = 'C:\Program Files\Microsoft Visual Studio\18\Community\VC\Tools\MSVC\14.51.36231\bin\Hostx64\arm64\lib.exe'
rustflags = ['-C', 'link-arg=/OPT:REF',
             '-C', 'link-arg=/OPT:ICF',
             '-C', 'link-arg=/DEBUG:NONE',
            ]

#---------------------------------- Android
[target.aarch64-linux-android]
linker    = '/home/elad/toolchains/android-ndk-r30/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang'
ar        = '/home/elad/toolchains/android-ndk-r30/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar'
rustflags = ['-C', 'link-arg=-Wl,--gc-sections']

[target.i686-linux-android]
linker    = '/home/elad/toolchains/android-ndk-r30/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android21-clang'
ar        = '/home/elad/toolchains/android-ndk-r30/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar'
rustflags = ['-C', 'link-arg=-Wl,--gc-sections']

[target.x86_64-linux-android]
linker    = '/home/elad/toolchains/android-ndk-r30/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android21-clang'
ar        = '/home/elad/toolchains/android-ndk-r30/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar'
rustflags = ['-C', 'link-arg=-Wl,--gc-sections']

[target.armv7-linux-androideabi]
linker    = '/home/elad/toolchains/android-ndk-r30/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang'
ar        = '/home/elad/toolchains/android-ndk-r30/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar'
rustflags = ['-C', 'link-arg=-Wl,--gc-sections']

#---------------------------------- Linux (gnu)
[target.aarch64-unknown-linux-gnu]
linker    = '/home/elad/toolchains/aarch64-unknown-linux-gnu/bin/aarch64-unknown-linux-gnu-clang'
ar        = '/home/elad/toolchains/aarch64-unknown-linux-gnu/bin/llvm-ar'
rustflags = ['-C', 'link-arg=-Wl,--gc-sections']

[target.i686-unknown-linux-gnu]
linker    = '/home/elad/toolchains/i686-unknown-linux-gnu/bin/i686-unknown-linux-gnu-clang'
ar        = '/home/elad/toolchains/i686-unknown-linux-gnu/bin/llvm-ar'
rustflags = ['-C', 'link-arg=-Wl,--gc-sections']

[target.powerpc-unknown-linux-gnu]
linker    = '/home/elad/toolchains/powerpc-unknown-linux-gnu/bin/powerpc-unknown-linux-gnu-clang'
ar        = '/home/elad/toolchains/powerpc-unknown-linux-gnu/bin/llvm-ar'
rustflags = ['-C', 'link-arg=-Wl,--gc-sections']

[target.powerpc64-unknown-linux-gnu]
linker    = '/home/elad/toolchains/powerpc64-unknown-linux-gnu/bin/powerpc64-unknown-linux-gnu-clang'
ar        = '/home/elad/toolchains/powerpc64-unknown-linux-gnu/bin/llvm-ar'
rustflags = ['-C', 'link-arg=-Wl,--gc-sections']

[target.powerpc64le-unknown-linux-gnu]
linker    = '/home/elad/toolchains/powerpc64le-unknown-linux-gnu/bin/powerpc64le-unknown-linux-gnu-clang'
ar        = '/home/elad/toolchains/powerpc64le-unknown-linux-gnu/bin/llvm-ar'
rustflags = ['-C', 'link-arg=-Wl,--gc-sections']

[target.x86_64-unknown-linux-gnu]
linker    = '/home/elad/toolchains/x86_64-unknown-linux-gnu/bin/x86_64-unknown-linux-gnu-clang'
ar        = '/home/elad/toolchains/x86_64-unknown-linux-gnu/bin/llvm-ar'
rustflags = ['-C', 'link-arg=-Wl,--gc-sections']

[target.armv7-unknown-linux-gnueabi]
linker    = '/home/elad/toolchains/armv7-unknown-linux-gnueabi/bin/armv7-unknown-linux-gnueabi-clang'
ar        = '/home/elad/toolchains/armv7-unknown-linux-gnueabi/bin/llvm-ar'
rustflags = ['-C', 'link-arg=-Wl,--gc-sections']

[target.armv7-unknown-linux-gnueabihf]
linker    = '/home/elad/toolchains/armv7-unknown-linux-gnueabihf/bin/armv7-unknown-linux-gnueabihf-clang'
ar        = '/home/elad/toolchains/armv7-unknown-linux-gnueabihf/bin/llvm-ar'
rustflags = ['-C', 'link-arg=-Wl,--gc-sections']

#---------------------------------- Linux (musl)
[target.aarch64-unknown-linux-musl]
linker    = '/home/elad/toolchains/aarch64-unknown-linux-musl/bin/aarch64-unknown-linux-musl-clang'
ar        = '/home/elad/toolchains/aarch64-unknown-linux-musl/bin/llvm-ar'
rustflags = ['-C', 'link-arg=-static', '-C', 'link-arg=-Wl,--gc-sections']

[target.i686-unknown-linux-musl]
linker    = '/home/elad/toolchains/i686-unknown-linux-musl/bin/i686-unknown-linux-musl-clang'
ar        = '/home/elad/toolchains/i686-unknown-linux-musl/bin/llvm-ar'
rustflags = ['-C', 'link-arg=-static', '-C', 'link-arg=-Wl,--gc-sections']

[target.powerpc64-unknown-linux-musl]
linker    = '/home/elad/toolchains/powerpc64-unknown-linux-musl/bin/powerpc64-unknown-linux-musl-clang'
ar        = '/home/elad/toolchains/powerpc64-unknown-linux-musl/bin/llvm-ar'
rustflags = ['-C', 'link-arg=-static', '-C', 'link-arg=-Wl,--gc-sections']

[target.powerpc64le-unknown-linux-musl]
linker    = '/home/elad/toolchains/powerpc64le-unknown-linux-musl/bin/powerpc64le-unknown-linux-musl-clang'
ar        = '/home/elad/toolchains/powerpc64le-unknown-linux-musl/bin/llvm-ar'
rustflags = ['-C', 'link-arg=-static', '-C', 'link-arg=-Wl,--gc-sections']

[target.x86_64-unknown-linux-musl]
linker    = '/home/elad/toolchains/x86_64-unknown-linux-musl/bin/x86_64-unknown-linux-musl-clang'
ar        = '/home/elad/toolchains/x86_64-unknown-linux-musl/bin/llvm-ar'
rustflags = ['-C', 'link-arg=-static', '-C', 'link-arg=-Wl,--gc-sections']

[target.armv7-unknown-linux-musleabi]
linker    = '/home/elad/toolchains/armv7-unknown-linux-musleabi/bin/armv7-unknown-linux-musleabi-clang'
ar        = '/home/elad/toolchains/armv7-unknown-linux-musleabi/bin/llvm-ar'
rustflags = ['-C', 'link-arg=-static', '-C', 'link-arg=-Wl,--gc-sections']

[target.armv7-unknown-linux-musleabihf]
linker    = '/home/elad/toolchains/armv7-unknown-linux-musleabihf/bin/armv7-unknown-linux-musleabihf-clang'
ar        = '/home/elad/toolchains/armv7-unknown-linux-musleabihf/bin/llvm-ar'
rustflags = ['-C', 'link-arg=-static', '-C', 'link-arg=-Wl,--gc-sections']


[env]
#---------------------------------- Android
CC_aarch64_linux_android          = { force = true,  value = '/home/elad/toolchains/android-ndk-r30/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang'     }
AR_aarch64_linux_android          = { force = true,  value = '/home/elad/toolchains/android-ndk-r30/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar'                           }
CC_i686_linux_android             = { force = true,  value = '/home/elad/toolchains/android-ndk-r30/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android21-clang'        }
AR_i686_linux_android             = { force = true,  value = '/home/elad/toolchains/android-ndk-r30/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar'                           }
CC_x86_64_linux_android           = { force = true,  value = '/home/elad/toolchains/android-ndk-r30/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android21-clang'      }
AR_x86_64_linux_android           = { force = true,  value = '/home/elad/toolchains/android-ndk-r30/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar'                           }
CC_armv7_linux_androideabi        = { force = true,  value = '/home/elad/toolchains/android-ndk-r30/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang'  }
AR_armv7_linux_androideabi        = { force = true,  value = '/home/elad/toolchains/android-ndk-r30/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar'                           }
#---------------------------------- Linux (gnu)
CC_aarch64_unknown_linux_gnu      = { force = true,  value = '/home/elad/toolchains/aarch64-unknown-linux-gnu/bin/aarch64-unknown-linux-gnu-clang'                               }
AR_aarch64_unknown_linux_gnu      = { force = true,  value = '/home/elad/toolchains/aarch64-unknown-linux-gnu/bin/llvm-ar'                                                       }
CC_i686_unknown_linux_gnu         = { force = true,  value = '/home/elad/toolchains/i686-unknown-linux-gnu/bin/i686-unknown-linux-gnu-clang'                                     }
AR_i686_unknown_linux_gnu         = { force = true,  value = '/home/elad/toolchains/i686-unknown-linux-gnu/bin/llvm-ar'                                                          }
CC_powerpc_unknown_linux_gnu      = { force = true,  value = '/home/elad/toolchains/powerpc-unknown-linux-gnu/bin/powerpc-unknown-linux-gnu-clang'                               }
AR_powerpc_unknown_linux_gnu      = { force = true,  value = '/home/elad/toolchains/powerpc-unknown-linux-gnu/bin/llvm-ar'                                                       }
CC_powerpc64_unknown_linux_gnu    = { force = true,  value = '/home/elad/toolchains/powerpc64-unknown-linux-gnu/bin/powerpc64-unknown-linux-gnu-clang'                           }
AR_powerpc64_unknown_linux_gnu    = { force = true,  value = '/home/elad/toolchains/powerpc64-unknown-linux-gnu/bin/llvm-ar'                                                     }
CC_powerpc64le_unknown_linux_gnu  = { force = true,  value = '/home/elad/toolchains/powerpc64le-unknown-linux-gnu/bin/powerpc64le-unknown-linux-gnu-clang'                       }
AR_powerpc64le_unknown_linux_gnu  = { force = true,  value = '/home/elad/toolchains/powerpc64le-unknown-linux-gnu/bin/llvm-ar'                                                   }
CC_x86_64_unknown_linux_gnu       = { force = true,  value = '/home/elad/toolchains/x86_64-unknown-linux-gnu/bin/x86_64-unknown-linux-gnu-clang'                                 }
AR_x86_64_unknown_linux_gnu       = { force = true,  value = '/home/elad/toolchains/x86_64-unknown-linux-gnu/bin/llvm-ar'                                                        }
CC_armv7_unknown_linux_gnueabi    = { force = true,  value = '/home/elad/toolchains/armv7-unknown-linux-gnueabi/bin/armv7-unknown-linux-gnueabi-clang'                           }
AR_armv7_unknown_linux_gnueabi    = { force = true,  value = '/home/elad/toolchains/armv7-unknown-linux-gnueabi/bin/llvm-ar'                                                     }
CC_armv7_unknown_linux_gnueabihf  = { force = true,  value = '/home/elad/toolchains/armv7-unknown-linux-gnueabihf/bin/armv7-unknown-linux-gnueabihf-clang'                       }
AR_armv7_unknown_linux_gnueabihf  = { force = true,  value = '/home/elad/toolchains/armv7-unknown-linux-gnueabihf/bin/llvm-ar'                                                   }
#---------------------------------- Linux (musl)
CC_aarch64_unknown_linux_musl     = { force = true,  value = '/home/elad/toolchains/aarch64-unknown-linux-musl/bin/aarch64-unknown-linux-musl-clang'                             }
AR_aarch64_unknown_linux_musl     = { force = true,  value = '/home/elad/toolchains/aarch64-unknown-linux-musl/bin/llvm-ar'                                                      }
CC_i686_unknown_linux_musl        = { force = true,  value = '/home/elad/toolchains/i686-unknown-linux-musl/bin/i686-unknown-linux-musl-clang'                                   }
AR_i686_unknown_linux_musl        = { force = true,  value = '/home/elad/toolchains/i686-unknown-linux-musl/bin/llvm-ar'                                                         }
CC_powerpc64_unknown_linux_musl   = { force = true,  value = '/home/elad/toolchains/powerpc64-unknown-linux-musl/bin/powerpc64-unknown-linux-musl-clang'                         }
AR_powerpc64_unknown_linux_musl   = { force = true,  value = '/home/elad/toolchains/powerpc64-unknown-linux-musl/bin/llvm-ar'                                                    }
CC_powerpc64le_unknown_linux_musl = { force = true,  value = '/home/elad/toolchains/powerpc64le-unknown-linux-musl/bin/powerpc64le-unknown-linux-musl-clang'                     }
AR_powerpc64le_unknown_linux_musl = { force = true,  value = '/home/elad/toolchains/powerpc64le-unknown-linux-musl/bin/llvm-ar'                                                  }
CC_x86_64_unknown_linux_musl      = { force = true,  value = '/home/elad/toolchains/x86_64-unknown-linux-musl/bin/x86_64-unknown-linux-musl-clang'                               }
AR_x86_64_unknown_linux_musl      = { force = true,  value = '/home/elad/toolchains/x86_64-unknown-linux-musl/bin/llvm-ar'                                                       }
CC_armv7_unknown_linux_musleabi   = { force = true,  value = '/home/elad/toolchains/armv7-unknown-linux-musleabi/bin/armv7-unknown-linux-musleabi-clang'                         }
AR_armv7_unknown_linux_musleabi   = { force = true,  value = '/home/elad/toolchains/armv7-unknown-linux-musleabi/bin/llvm-ar'                                                    }
CC_armv7_unknown_linux_musleabihf = { force = true,  value = '/home/elad/toolchains/armv7-unknown-linux-musleabihf/bin/armv7-unknown-linux-musleabihf-clang'                     }
AR_armv7_unknown_linux_musleabihf = { force = true,  value = '/home/elad/toolchains/armv7-unknown-linux-musleabihf/bin/llvm-ar'                                                  }
